### ISSUE TITLE
Plugins cannot be specified via a filepath

### ISSUE THREAD

**Issue by kgryte** [wooorm/unified-args#1]
Currently, plugins are specified according to the plugin name. From that name, `unified` (via dependents) resolves a plugin, in a manner somewhat akin to the node module resolution algorithm.

The problem here is that you must provide a name, and a name only. I cannot provide the `path` to a plugin, similar to the way [browserify](https://github.com/substack/node-browserify) allows a user to specify a plugin.

While plugins will frequently be from external sources and thus installed in, say, `node_modules` using the naming convention `remark-*`, users may want to provide local plugins without the need of putting that plugin in a "special" place for `unified` to find.

And while the `load-plugin` module allows for specifying a directory as a starting point, this is not accessible from the CLI.

Thus, a useful improvement would be to allow plugins to be specified via filepaths, not just by name.

**Comment by wooorm** [comment]
This _should_ mostly be ok, although I changed some stuff recently.

Could you show me your file structure?

**Comment by kgryte** [comment]
@wooorm the basic structure is

``` text
bin/
examples/
lib/node_modules/**/
node_modules/
test/
tools/remark/plugins
```

I would like to be able to use the plugins from the separate tools directory, which are highly application specific. Hence, being able to do

``` bash
$ remark . --use ./tools/remark/plugins/remark-foo-bar --use ./tools/remark/plugins/remark-beep-boop
```

would be useful.

**Comment by wooorm** [comment]
Could you run with `DEBUG="*" remark ...`, and show me the output? To my knowledge this should be OK.

**Comment by kgryte** [comment]
@wooorm can confirm it **does** work. The docs are a bit confusing in this regard, as this type of usage is no where mentioned or shown. Might be good to mention that this is possible in the docs.

**Comment by wooorm** [comment]
Great! Do you have a suggested place for that? Where did you look?

**Comment by Planeshifter** [comment]
`remark-cli` redirects one to `unified-args` for explanations on all available options. The `--use <plugin>` section is what we read. One example there that involves a file path would be helpful, I think.

**Comment by kgryte** [comment]
Also, not obvious from reading the [algorithm](https://github.com/wooorm/load-plugin#algorithm) for plugin loading that `$name` can effectively be a relative path.

**Comment by wooorm** [comment]
Thanks both!

**Comment by kgryte** [comment]
Thanks for updating the docs!
