### ISSUE TITLE
Clarification on behaviour with nested directories

### ISSUE THREAD

**Issue by brendo** [wooorm/unified-args#15]
If I have a directory with the following structure:

```
- in/
    - index.md
    - hello.jpg
    - functions/
        - index.md
```

And I invoke `remark-cli` from a parent directory with `remark in -o out`, I was expecting that the `out/` directory would contain the `index.md` file, and a new folder `functions` that also contained an `index.md` file.

I'd hope that `hello.jpg` would make it there, but I doubt it as it's not markdown at all and probably out of scope for remark to handle.

Nevertheless, instead I get this error:

```
index.md
  1:1  error  Error: Cannot write multiple files to single output: /Users/brendanabbott/Sites/out
    at done (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/copy.js:58:19)
    at onstatparent (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/copy.js:52:7)
    at FSReqWrap.oncomplete (fs.js:153:5)

functions/index.md
  1:1  error  Error: Cannot write multiple files to single output: /Users/brendanabbott/Sites/out
    at done (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/copy.js:58:19)
    at onstatparent (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/copy.js:52:7)
    at FSReqWrap.oncomplete (fs.js:153:5)
```
Should this work?

**Comment by wooorm** [comment]
Hi @brendo! :wave:

`--output` does not create (intermediary) output directories, and I feel that’s correctly described [in its docs](https://github.com/unifiedjs/unified-args#--output-path). Did you see those? Do you have suggestions?

And you’re right about `hello.jpg`, that’s indeed beyond the scope of a markdown processor!

P.S. I personally use remark-cli/rehype-cli more for linting, and roll my own process for sites, for example [like this](https://github.com/unifiedjs/unifiedjs.github.io/blob/src/script/index.js).

**Comment by brendo** [comment]
Hi!

I read the following, and while I understood it, I wondered if the behaviour would be different if it didn't point to an existing directory, so I just thought I'd ask :)

> If output is given with path and it points to an existing directory, files are written to that directory (intermediate directories are not created)

Many thanks for that link, that's quite insightful actually and something similar would suit my use case very well!

**Comment by wooorm** [comment]
No problem, thanks for asking. If you feel this should be in here, we can talk about it.

> Many thanks for that link, that's quite insightful actually and something similar would suit my use case very well!

Glad to hear! Let me know what you come up with!
