### ISSUE TITLE
Error: Cannot write multiple files to single output:

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/unified-args#17]
If you have a git directory with a file "Readme.md" in a folder "something/", and change the file name to "README.md", then linting will fail with `remark . -qfo` with the error `Error: Cannot write multiple files to single output:`

**Comment by wooorm** [comment]
@niftylettuce This sound horrible!

But you description is also a bit vague, how could I reproduce it? Which file is renamed? What exactly are you running so I can check this too?

**Comment by niftylettuce** [comment]
I'm using `lint-staged` with `remark -qfo` as the command for when `*.md` files are changed.

(e.g. my package.json)
```json
  "lint-staged": {
    "*.{js,jsx,mjs,ts,tsx,css,less,scss,json,graphql}": [
      "prettier --write --single-quote --trailing-comma none",
      "git add"
    ],
    "*.md": ["git add", "remark -qfo"]
  },
```

Maybe this is just a lint-staged thing only?

**Comment by niftylettuce** [comment]
Also the file I'm renaming is `somedir/Readme.md` > `somedir/README.md`.

**Comment by wooorm** [comment]
Could it be related to lint-staged? I know that Git doesn’t automatically track a filename that changes capitalisation?

**Comment by niftylettuce** [comment]
seems like it is lint-staged... if I run `remark . -qfo` I don't get an error.  though I wonder if it's because of the old cache or something...

**Comment by wooorm** [comment]
remark itself doesn’t cache anything! I think this is inherent to Git. Maybe lint-staged can fix this? There’s nothing in remark that should produce [this error](https://github.com/unifiedjs/unified-engine/blob/d25a491e9a32ed573c11b4c04c498983ded4d55e/lib/file-pipeline/copy.js#L57-L59) normally. 🤷‍♂️
