### ISSUE TITLE
Passing string or number options to --use

### ISSUE THREAD

**Issue by cl8n** [wooorm/unified-args#26]
right now, --use can take a format like this: `toc=max-depth:3` with the part after equals sign being json options. however a lot of remark plugins take a string or number as an option rather than an object, and from what I can tell there's no way to pass those options in.

for example I'd like to do `--use lint-list-item-indent=space`, or `--use lint-blockquote-indentation=2`

**Comment by wooorm** [comment]
Hi there! That’s correct. Most plugins use objects. For legacy reasons, lint rules don’t. For a solution, can you use config files instead?

**Comment by cl8n** [comment]
ah alright if it's just a legacy thing that seems fine. can use config files instead 👍
